"""Utilities for the nbdev library."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/13_nbdev.ipynb.

# %% auto 0
__all__ = ['nbdev_config_file', 'is_nbdev']

# %% ../nbs/13_nbdev.ipynb
from .basics import Path

# %% ../nbs/13_nbdev.ipynb
_nbdev_cfg_name = 'settings.ini'

def nbdev_config_file(cfg_name=_nbdev_cfg_name, path=None):
    "Get the nbdev config file path"
    cfg_path = path = Path.cwd() if path is None else Path(path)
    while cfg_path != cfg_path.parent and not (cfg_path/cfg_name).exists(): cfg_path = cfg_path.parent
    if not (cfg_path/cfg_name).exists(): cfg_path = path
    return cfg_path/cfg_name

# %% ../nbs/13_nbdev.ipynb
def is_nbdev(): 
    "Checks if the current directory is in a nbdev project."
    return nbdev_config_file().exists()
